@startuml listado_compras

title Diagrama de Secuencia: Listar Compras

actor Administrador
boundary "iu_listadoCompras:IU_ListadoCompras" as IU
control "cu_listarCompras:CU_ListarCompras" as CU
entity "cat_comp:CatalogoCompras" as CAT

== Solicitar listado ==
Administrador -> IU: ingresarFiltros(filtros, pagina)
activate IU

IU -> CU: solicitarListado(filtros, pagina)
activate CU

CU -> CAT: obtenerCompras(filtros, pagina)
activate CAT

CAT --> CU: listaCompras, total
deactivate CAT

CU --> IU: resultadoListado(listaCompras, total)
deactivate CU

IU --> Administrador: mostrarListado(listaCompras, paginado)
deactivate IU


alt Búsqueda sin resultados
    CAT --> CU: listaCompras = vacia, total = 0
    CU --> IU: resultadoVacio()
    IU --> Administrador: "No se encontraron compras"
end

alt Error al cargar lista
    CAT --> CU: errorConsulta
    CU --> IU: informarError()
    IU --> Administrador: "Error al cargar la lista"
end

@enduml
