@startuml compra

title Diagrama de Secuencia: Registrar Compra

actor Administrador
participant Sistema
participant "cat_prov:Catálogo_prov" as Cat_prov
participant "cat_fp:Catálogo_forma_pago" as Cat_fp
participant "multi:Multiobjeto" as MULT

== Registro de Proveedor ==
loop hasta datos correctos
    Administrador -> Sistema: Ingresar_dato_proveedor(nombre)
    activate Sistema
    Sistema -> Cat_prov: Buscar_proveedor(CUIT)
    activate Cat_prov
    Cat_prov --> Sistema: Proveedor_encontrado | null
    deactivate Cat_prov

    alt Proveedor no encontrado
        Sistema --> Administrador: <<"Datos incorrectos">>
        deactivate Sistema
    end    
end

== Registro de Forma de Pago ==
loop hasta seleccion valid
Administrador -> Sistema:Seleccionar_forma_de_pago(Efectivo | Tarjeta | Transferencia)
activate Sistema
Sistema -> Cat_fp: Validar_forma_pago()
activate Cat_fp
Cat_fp --> Sistema: Resultado_validación
deactivate Cat_fp

opt Forma de pago inválida
    Sistema --> Administrador: <<"Datos incorrectos">>
    deactivate Sistema
end


== creación Ítem de Compra ==
loop tantas veces como se desee
    create "item_compra:Item_compra" as IC
    Administrador -> IC: Crear_item_compra(nombre, tipo, marca, cantidad, precio unitario)
    activate IC
    activate Sistema
    Sistema -> MULT: Guardar_item_compra()
    Sistema --> Administrador: NULL
    deactivate Sistema
    deactivate IC
@enduml