@startuml Producto
title Diagrama de Secuencia - Gestión de Productos

actor Administrador
participant "Sistema" as Sistema
participant "catalogo" as C
participant "multiobjeto" as MO

== Registro de Producto ==

Administrador -> Sistema: Registrar_producto (nombre, cantidad, precio)
activate Sistema

alt Producto Registrado
    Sistema --> Administrador: <<"Producto registrado, actualizar stock">>
else Producto ya existe
    Sistema --> Administrador: <<"El producto ya existe, registrar nuevo producto">>
deactivate Sistema
end


Sistema --> Administrador: <<"formulario de registro">>


loop Hasta completar datos
    Sistema --> Administrador: <<"Error">>
    Sistema --> Administrador: <<"Completar datos">>
end


Administrador -> Sistema: Ingresar_datos_producto()
activate Sistema
Sistema -> MO: Almacenar datos del producto
activate MO

alt Error en almacenamiento
    MO --> Sistema: <<Error>>
    deactivate MO
    Sistema --> Administrador: <<"Error en almacenamiento">>
else Almacenamiento exitoso
    MO --> Sistema: <<"Confirmación almacenamiento">>
    deactivate MO
    Sistema --> Administrador: <<"Mostrar mensaje de confirmación">>
end
deactivate Sistema

== Consulta de Productos ==

Administrador -> Sistema: Solicitar_lista_productos()
activate Sistema

C --> Sistema: <<"Lista de productos">>
deactivate C
Sistema --> Administrador: <<"Mostrar lista de productos\n(en stock y faltantes)">>
deactivate Sistema

== Modificación de Productos ==

Administrador -> Sistema: Modificar_precio_producto()
activate Sistema
Sistema -> MO: Actualizar_precio_producto()
activate MO
MO --> Sistema: <<"Confirmación de actualización">>
deactivate MO
Sistema --> Administrador: <<"Mostrar mensaje de confirmación">>
deactivate Sistema

opt Producto fuera de venta
    Administrador -> Sistema: Marcar producto como fuera de venta
    activate Sistema
    Sistema -> MO: Actualizar estado del producto
    activate MO
    MO --> Sistema: <<"Confirmación de actualización">>
    deactivate MO
    Sistema --> Administrador: <<"Mostrar mensaje de confirmación">>
    
end

@enduml
