@startuml listado_proveedores

title Diagrama de Secuencia: Listar Proveedores

actor Administrador
boundary "iu_listadoProv:IU_ListadoProveedores" as IU
control "cu_listarProv:CU_ListarProveedores" as CU
entity "cat_prov:CatalogoProveedores" as CAT

== Solicitar listado ==
Administrador -> IU: ingresarFiltros(filtros, pagina)
activate IU

IU -> CU: solicitarListado(filtros, pagina)
activate CU

CU -> CAT: obtenerProveedores(filtros, pagina)
activate CAT

CAT --> CU: listaProveedores, total


CU --> IU: resultadoListado(listaProveedores, total)


IU --> Administrador: mostrarListado(listaProveedores, paginado)


alt Búsqueda sin resultados
    CAT --> CU: listaProveedores = vacia, total = 0
    CU --> IU: resultadoVacio()
    IU --> Administrador: mostrarMensaje("No se encontraron proveedores")
end

alt Error al cargar lista
    CAT --> CU: errorConsulta
    deactivate CAT
    CU --> IU: informarError()
    deactivate CU
    IU --> Administrador: mostrarMensaje("Error al cargar la lista")
    deactivate IU
end

@enduml
