@startuml registrar_proveedor

title Diagrama de Secuencia: Registrar Proveedor

actor Administrador
boundary "iu_registrarProv:IU_RegistrarProveedor" as IU
control "cu_registrarProv:CU_RegistrarProveedor" as CU
entity "proveedor:Proveedor" as P
entity "cat_prov:CatalogoProveedores" as CAT

== Ingreso de Datos ==
Administrador -> IU: ingresarDatos(nombre,CUIT,telefono,email)
activate IU

IU -> CU: registrarProveedor(datos)
activate CU

CU -> CU: validarDatos(datos)

alt Datos inválidos
    CU --> IU: informarError()
    IU --> Administrador: mostrarMensaje("Datos inválidos")
else Datos válidos

    create P
    CU -> P: inicializar(nombre,CUIT,telefono,email)

    CU -> CAT: guardarProveedor(P)
    activate CAT
    CAT --> CU: proveedorGuardado
    deactivate CAT

    CU --> IU: registroExitoso()
    IU --> Administrador: mostrarConfirmacion()

end

deactivate CU
deactivate IU

@enduml
