@startuml gomeria

    class Transaccion {
        - numero: Int
        - fecha: Date
        - forma_de_pago: str

        + procesar(): Void 
        + movimiento_stock(): Void
        + calcular_total(): Void 
    }

    class Compra {
        - proveedor: List<<Proveedor>>

        + registrar_compra(): Void 
        + modificar_compra(): Void
    }

    class Venta {
        - cliente: List<<Cliente>>

        + registrar_venta(): Void 
        + modificar_venta(): Void
        + calcular_ganancia(): Void 
        + emitir_factura(): Void
    }

    class Item {
        - producto: List<<Producto>>
        - cantidad: Int
        - precio: Float
        - descuento: Float
        - nombre: str
        - tipo : str
        - marca: str

        + registrar_item():
        + modificar_item():
        + eliminar_item():
    }

    class Persona {
        - nombre: String
        - apellido: String
        - dni: Int
        - direccion: String
    }

    class Proveedor {
    
        ' - lista_precios: Map<String, Float>

        ' + mostrar_lista_precios(): Void
    }

    class Cliente {
        
        ' - lista_precios: Map<String, Float>

        ' + mostrar_lista_precios(): Void
    }

    class Producto {
        - Nombre: String 
        - Precio: Float 
        - Tipo: String 
        - Marca: String 
        - Cantidad: Int 
        - Proveedor: List<<Proveedor>>
        
        + registrar_producto(): Void 
        + modificar_producto(): Void 
        + eliminar_producto(): Void
        + calcular_precio(): Void
        + filtrar_productos(): Void
    }


    Persona <|-- Proveedor
    Persona <|-- Cliente

    Transaccion "1..*" <|-- "1..*" Venta
    Transaccion "1..*" <|-- "1..*" Compra

    Compra "1" -- "1..*" Item
    Venta "1" -- "1..*" Item

    Compra "1" -- "1..*" Proveedor
    Venta "1" -- "1..*" Cliente

    Item "1" -- "1" Producto


@enduml