@startchen

entity proveedores {
  id: INT <<key>>
  nombre: VARCHAR
  CUIT: INT
  telefono: INT
  correo electronico: VARCHAR
}

entity cuentas_corrientes {
  id: INT <<key>>
  nombre: VARCHAR
  DNI: INT 
  telefono: INT
  correo electronico: VARCHAR
}

entity productos {
  id: INT <<key>>
  nombre: VARCHAR
  precio: FLOAT
  tipo: VARCHAR
  codigo: INT 
  descripcion: VARCHAR
}

entity historial_pagos{
id: Int <<key>>
fk_id_cuenta_corriente: Int
pago: float
fecha: date
hora: time
monto: float
forma_de_pago: VARCHAR
}


relationship historial_ventas{
id: Int <<key>>
fk_id_proveedore: Int
compra: float
fecha: date
hora: time
cantidad: Int
precio_total: Int
}

relationship historial_compras{
id: Int <<key>>
fk_id_cuenta_corriente: Int
compra: float
fecha: date
hora: time
cantidad: Int
precio_total: Int
}

proveedores -N- historial_compras
historial_compras -N- productos

cuentas_corrientes -N- historial_ventas
historial_ventas -N- productos

historial_ventas -N- historial_pagos


@endchen
